### ISSUE TITLE
Errors when trying to run example

### ISSUE THREAD

**Issue by MisaelK** [ceyzeriat/joystick#1]
I tried running the example provided in the `README` file, and the one in the joystick folder (`example.py`), without success.

When executing, a blank tkinter matplotlib window opens and then Python crashes with the following message:
```
Fatal Python error: PyEval_RestoreThread: NULL tstate

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

Using `pdb` to debug it, I get this additional info:
```
> c:\users\temp\documents\sourcecode\python\!external\joystick_example.py(1)<module>()
-> import joystick as jk
(Pdb) r
--Return--
> c:\users\temp\documents\sourcecode\python\!external\joystick_example.py(53)<module>()->None
-> t.start()
(Pdb) n
--Return--
> <string>(1)<module>()->None
(Pdb) 
The program finished and will be restarted
```
An additional `NameError: global name 'jk' is not defined` error is shown, which I can fix by repeating the imports (`joystick as jk`, `numpy as np`, `time`) inside the `_generate_fake_data(self):` function. 

This is my main Python version: `Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32`. I'm using Windows 7 x64.
After upgrading and retesting, my relevant libs are: `matplotlib (1.5.3)`, `numpy (1.11.2)`.

I also tested it (with similar results) with `WinPython-64bit-2.7.10.3` and `WinPython-32bit-3.4.3.6` (although no error is shown with this version).

If there's anything you need, please tell me and I'll try to provide it.

Thanks in advance.

**Comment by ceyzeriat** [comment]
Hi @MisaelK,
Thanks for your feedback!
That error doesn't sound good! Looks like I should have tested joystick on Windows too (only Unix) :/.
I do have `NameError: global name 'jk' is not defined` error on Unix that happens when a frame is closed while running (which is a bit brutal - that's what happens in your case): the namespace is dumped but the updating function is still cached, leading to the `NameError` when it tries to run again. I would say that this is not the main issue you experience here however.
I do know that threads on windows are a bit tricky to implement with python, I would be the issue comes from there.
Alright, I took the point, but I have a BIG deadline in less than a week - I'll have a close look after the 11th.
Sorry for the inconvenience!
Guillaume

**Comment by ceyzeriat** [comment]
Hi @MisaelK,
Thanks for your feedback!
That error doesn't sound good! Looks like I should have tested joystick on Windows too (only Unix) :/.
I do have `NameError: global name 'jk' is not defined` error on Unix that happens when a frame is closed while running (which is a bit brutal - that's what happens in your case): the namespace is dumped but the updating function is still cached, leading to the `NameError` when it tries to run again. I would say that this is not the main issue you experience here however.
I do know that threads on windows are a bit tricky to implement with python, I would bet the issue comes from there.
Alright, I took the point, but I have a BIG deadline in less than a week - I'll have a close look after the 11th.
Sorry for the inconvenience!
Guillaume

ps: I was thinking about a few test-cases before I can dive into it. Maybe try to run the `test` class only with the `_init` method (remove the `_generate_fake_data` method), and create the object `t = test()`. Just this should display the 2 frames - no threading involved.

**Comment by MisaelK** [comment]
Thanks for the fast response, @ceyzeriat!

I did some more tests, and found the simplest example that fails on my setup with the same error:
```python
import joystick
joystick.Graph("test")
```

I also tried out some pure matplotlib examples and they work fine, as long as I use the TkAgg engine (which is what joystick uses, anyway).

There's no rush, take your time! 
Thanks again!

**Comment by ceyzeriat** [comment]
Alright, so I looked at this a bit closer.
I have tried both python 3.5.2 and 2.7.12 with the following setup: win7 x64, anaconda 4.2.0 (matplotlib 1.5.2, numpy 1.11.1) and the full example worked fine straight out of the box in both cases. (I'm actually pleasantly surprised that there was no issue with threads!)
So that's strange you have this weird thing happening, even with the simplest `joystick.Graph("test")` command.
Tkinter.TclVersion gives me 8.5 on python2.7, and 8.6 on python 3.5. Can you check that on your side?
These 3 libraries and `Thread` from `multiprocessing` are about all that's imported in `joystick`, so if it not a Tkinter version issue, then this doesn't smell good :)

**Comment by MisaelK** [comment]
Well, something's weird definitely going on.

I just tested the simple `joystick.Graph("test")` example on another Windows computer (a 32 bits one this time) and the error keeps happening. However, if I type the same commands in an interactive Python console, it works! Even the full example works (which I pasted into an IPython console).

I have Tkinter 8.5. I suppose it's paired to the Python version, since it's a builtin library.

Maybe this is a specific problem with matplotlib? Also, I'll try with Anaconda later, it could be a bad mix of libraries.

**Comment by ceyzeriat** [comment]
Hm, how were you executing the code initially? (if not through the console/ipython?)

`joystick` was designed to be interactive, such that the user can control and command the data-acquisition process while the display are updating. So it was really based on a use from the console.

Let's start from the beginning: what was your initial need from this library?

**Comment by MisaelK** [comment]
I did what I usually do: I save the example code in a `.py` file and then I run it using `python example.py`. It's a lot less cumbersome than copypasting the code each time.

My initial need was to graph some serial data coming from an Arduino (or rather, a custom board with an ATMega328p compatible with the Arduino library) in real time. My current solution is just logging all incoming data to a CSV file and then graph that using `matplotlib`, sometimes offline and sometimes live using matplotlib's `FuncAnimation`. This means using two different python processes, since there's two different `.py` files that only interact with each other through the CSV file.

**Comment by ceyzeriat** [comment]
If you run it using `python example.py`, that's from a terminal/console then, but outside a python environment?

I see 2 issues to that: 1) you have no control on the script anymore, since the OS terminal cannot access the variables into the python script - so I guess you chunk the `t = test()` and `t.start()` in the script, and then leave it going?, and 2) since the script is multi-threaded to let you have the hand on the simulation, then the script you launch from the OS terminal will terminate immediately after it is executed.

I suggest you leave everything you need to initialize and launch your script in the `example.py` and use the `run example.py` command in ipython. This will be equivalent to writing `python example.py`, except that you will be and remain in the python environment (ipython actually), where you can access and control the on-going simulation (i.e. the `t` variable).

I had a colleague who was exactly in the same case as what you try to achieve, read/write to a serial port. Since there can be only 1 process that opens the port, there was the to have some kind of multi-threaded application that can do both. He adopted this library as soon as I presented it to him :)

One way to build your serial-port script using `joystick` is to make a base-class that inherit from `joystick.Joystick`, and add all he required capabilities as methods/sub-classes
[hop.txt](https://github.com/ceyzeriat/joystick/files/531846/hop.txt)
 (cf file attached).

**Comment by MisaelK** [comment]
Ah, I see! I understand now. An interactive prompt is necessary to use `joystick` (and therefore run the examples).

So, there are two solutions:

1) Using IPython:
```
IPython
In [1]: run example.py
```

2) Using regular Python:
```
python -i example.py
```

Thanks for your time!

**Comment by ceyzeriat** [comment]
We both got misled by the weird error... strange it showed up this way.

Anyhow, happy it helped! Last stuff, if you have the choice, I advice `ipython` over `python -i` since it has a lot of nice features like auto-completion, help, etc :)
