### ISSUE TITLE
AttributeError: module 'matplotlib.backends' has no attribute 'backend_tkagg'

### ISSUE THREAD

**Issue by alberto-battistel** [ceyzeriat/joystick#4]
Hi,
I have this error when trying your example code (that on the readme.md).

It also issues a warning: 

> "UserWarning: This call to matplotlib.use() has no effect because the backend has already been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
> or matplotlib.backends is imported for the first time."

I do not really understand where the problem is.
can you help?

**Comment by ceyzeriat** [comment]
Hi,
The issue here is because you are using a python interpreter that is doing some imports (pylab) on the default matplotlib backend before joystick does its own imports: "the backend has already been chosen".
I guess you were using and IDE, or the console call "ipython --pylab"?
To fix that you need to either change your default backend in your IDE, or use a bare ipython interpreter (i.e. "ipython" in a terminal).
I recommend using a simple "ipython" command in the terminal that will do everything you expect, and nothing more :)

**Comment by alberto-battistel** [comment]
thank you very much for your quick answer.
But I still encounter problems. Now running from command line either python or with ipython (all 2 and 3 versions)I get:

> AttributeError:  'Axes' object has no attribute 'set_facecolor'

**Comment by ceyzeriat** [comment]
Hm this is interesting. What version of matplotlib have you got?
> import matplotlib
> matplotlib.__version__

**Comment by alberto-battistel** [comment]
> matplotlib.__version__
'1.5.1'

**Comment by ceyzeriat** [comment]
So indeed, 1.5.1 does not have the set_facecolor method, this explains it. The old method is ``set_axis_bgcolor``, deprecated since version matplolib 2.0.
The quick fix for you is update your matplotlib. Unless you have some very strange dependencies to an old matplotlib version, this is the way to go; matplotlib 2.0 has been around for a bit more than a year now so it is quite stable.
I will add a fall-back to the old method name on the set_facecolor call (graph.py line 135) so joystick is compatible with matplotlib 1.5.
It is an easy fix but I need to re-package the library, so I'll do it during the week.
If you have any other feedback (once it is working..), it will be appreciated :)
Cheers!

**Comment by ceyzeriat** [comment]
Hi,
This should be fixed now
Cheers

**Comment by alberto-battistel** [comment]
Fantastic now __it works__ everything fine.
_Summary:_

1. update _matplotlib_
2. if using an IDE like _spyder3_ deactivate support for matplotlib (in spyder Tools -> ipython console -> 
graphics) otherwise you get an error about preselected backend

**Comment by ceyzeriat** [comment]
Awesome!
I'll be happy to answer any other question.
Would you mind if I close the issue?
Cheers
ps: I'll add a word in the readme about the backend stuff
